### PR TITLE
Resolved crashes with compiler optimization set to "Fast"

### PR DESCRIPTION
**Pull request by chuckboris**
Refactored code into one line, which solved crashes with compiler optimization set to "Fast"

### CODE REVIEW

**Comment by salutis** [comment]
It's unreadable. 😞 What was the crash about?

**Comment by chuckboris** [comment]
Was assigning font in viewDidLoad like this

`label.font = label.font.monospacedDigitFont`

it worked fine in Debug configuration, but crashed on start on Release. Crash was "bad access".

**Comment by salutis** [comment]
I shipped apps with this, i.e. Release worked fine. I'm OK merging anything that works but it needs to be readable.

**Comment by chuckboris** [comment]
Interesting. I got it returned by app review, crashing on start. In fact the code is exactly the same, but written into single line without any intermediate variables. Seems to me like problem with swift compiler or something. Never mind, maybe someone will be able to find my solution and will save some time figuring it out.

**Comment by salutis** [comment]
If you can reproduce it, be sure to report to Swift team. Closing this one.

**Pull request closed without merging**
